/* data-text.js : contenus rédigés (originaux) */

/* Faux amis : en = mot anglais ; trap = traduction piège ; tru = vrai sens ; fr = mot français à traduire ; enFor = bonne traduction anglaise */
const FF=[
{en:'actual',trap:'actuel',tru:'réel',fr:'actuel',enFor:'current',ex:'The actual wind was stronger than forecast.',exfr:'Le vent réel était plus fort que prévu.'},
{en:'actually',trap:'actuellement',tru:'en fait',fr:'actuellement',enFor:'currently',ex:'Actually, we landed ten minutes early.',exfr:'En fait, nous avons atterri avec dix minutes d\'avance.'},
{en:'eventually',trap:'éventuellement',tru:'finalement',fr:'éventuellement',enFor:'possibly / if necessary',ex:'Eventually, we diverted to Lyon.',exfr:'Finalement, nous nous sommes déroutés vers Lyon.'},
{en:'command',trap:'les commandes (de vol)',tru:'un ordre',fr:'les commandes de vol',enFor:'flight controls',ex:'The captain gave the command to evacuate.',exfr:'Le commandant a donné l\'ordre d\'évacuer.'},
{en:'to assist',trap:'assister à',tru:'aider',fr:'assister à',enFor:'to attend',ex:'The ground crew assist the passengers.',exfr:'Le personnel au sol aide les passagers.'},
{en:'to attend',trap:'attendre',tru:'assister à',fr:'attendre',enFor:'to wait for',ex:'All pilots must attend the briefing.',exfr:'Tous les pilotes doivent assister au briefing.'},
{en:'to resume',trap:'résumer',tru:'reprendre',fr:'résumer',enFor:'to summarise',ex:'Resume own navigation.',exfr:'Reprenez votre navigation.'},
{en:'to prevent',trap:'prévenir (avertir)',tru:'empêcher',fr:'prévenir (avertir)',enFor:'to warn',ex:'The gust lock prevents the controls from moving.',exfr:'Le verrou de gouverne empêche les commandes de bouger.'},
{en:'sensible',trap:'sensible',tru:'raisonnable',fr:'sensible',enFor:'sensitive',ex:'It is sensible to carry extra fuel.',exfr:'Il est raisonnable d\'emporter du carburant en plus.'},
{en:'library',trap:'librairie',tru:'bibliothèque',fr:'librairie',enFor:'bookshop',ex:'The charts are in the flight library.',exfr:'Les cartes sont dans la bibliothèque de vol.'},
{en:'location',trap:'location (louer)',tru:'emplacement',fr:'location (louer)',enFor:'rental / hire',ex:'What is your present location?',exfr:'Quelle est votre position actuelle ?'},
{en:'to demand',trap:'demander',tru:'exiger',fr:'demander',enFor:'to ask',ex:'This situation demands immediate action.',exfr:'Cette situation exige une action immédiate.'},
{en:'to deceive',trap:'décevoir',tru:'tromper',fr:'décevoir',enFor:'to disappoint',ex:'Visual illusions can deceive a pilot.',exfr:'Les illusions visuelles peuvent tromper un pilote.'},
{en:'to pretend',trap:'prétendre',tru:'faire semblant',fr:'prétendre (affirmer)',enFor:'to claim',ex:'He pretended not to hear the call.',exfr:'Il a fait semblant de ne pas entendre l\'appel.'},
{en:'to realise',trap:'réaliser (accomplir)',tru:'se rendre compte',fr:'réaliser (accomplir)',enFor:'to carry out / to achieve',ex:'I realised that the fuel was low.',exfr:'Je me suis rendu compte que le carburant était bas.'},
{en:'to support',trap:'supporter (tolérer)',tru:'soutenir',fr:'supporter (tolérer)',enFor:'to bear / to put up with',ex:'The wing supports the weight of the aircraft.',exfr:'L\'aile soutient le poids de l\'avion.'},
{en:'fabric',trap:'fabrique (usine)',tru:'tissu',fr:'fabrique (usine)',enFor:'factory',ex:'The wings are covered with fabric.',exfr:'Les ailes sont recouvertes de toile.'},
{en:'lecture',trap:'lecture',tru:'cours magistral',fr:'lecture',enFor:'reading',ex:'The instructor gave a lecture on weather.',exfr:'L\'instructeur a donné un cours sur la météo.'},
{en:'chance',trap:'chance',tru:'risque, probabilité',fr:'chance',enFor:'luck',ex:'There is a chance of thunderstorms this afternoon.',exfr:'Il y a un risque d\'orages cet après-midi.'},
{en:'large',trap:'large',tru:'grand',fr:'large',enFor:'wide',ex:'A large aircraft needs a long runway.',exfr:'Un grand avion a besoin d\'une longue piste.'},
{en:'injury',trap:'injure',tru:'blessure',fr:'injure (insulte)',enFor:'insult',ex:'There were no injuries.',exfr:'Il n\'y a pas eu de blessés.'},
{en:'delay',trap:'délai',tru:'retard',fr:'délai (limite)',enFor:'deadline / time limit',ex:'Expect a thirty-minute delay.',exfr:'Attendez-vous à trente minutes de retard.'},
{en:'to control',trap:'contrôler (vérifier)',tru:'piloter, maîtriser',fr:'contrôler (vérifier)',enFor:'to check',ex:'The pilot controls the aircraft.',exfr:'Le pilote contrôle (maîtrise) l\'avion.'},
{en:'terrific',trap:'terrifiant',tru:'formidable',fr:'terrifiant',enFor:'terrifying',ex:'We had terrific visibility today.',exfr:'Nous avions une visibilité formidable aujourd\'hui.'},
{en:'to introduce',trap:'introduire',tru:'présenter',fr:'introduire (insérer)',enFor:'to insert',ex:'Let me introduce the crew.',exfr:'Laissez-moi vous présenter l\'équipage.'},
{en:'versatile',trap:'versatile',tru:'polyvalent',fr:'versatile (changeant)',enFor:'fickle / changeable',ex:'The Cessna 172 is a versatile aircraft.',exfr:'Le Cessna 172 est un avion polyvalent.'},
{en:'hardly',trap:'durement',tru:'à peine',fr:'durement',enFor:'hard',ex:'We hardly had any fuel left.',exfr:'Il nous restait à peine du carburant.'},
{en:'stage',trap:'stage',tru:'étape, phase',fr:'stage (formation)',enFor:'internship / work placement',ex:'Take-off is the first stage of a flight.',exfr:'Le décollage est la première phase d\'un vol.'},
{en:'pain',trap:'pain',tru:'douleur',fr:'pain (aliment)',enFor:'bread',ex:'The passenger complained of chest pain.',exfr:'Le passager s\'est plaint d\'une douleur à la poitrine.'},
{en:'sale',trap:'sale (pas propre)',tru:'vente',fr:'sale (pas propre)',enFor:'dirty',ex:'The aircraft is for sale.',exfr:'L\'avion est à vendre.'},
{en:'gentle',trap:'gentil',tru:'doux, progressif',fr:'gentil',enFor:'kind / nice',ex:'Make a gentle turn to the right.',exfr:'Faites un virage doux vers la droite.'},
{en:'formation',trap:'formation (instruction)',tru:'disposition, vol en groupe',fr:'formation (instruction)',enFor:'training',ex:'The two aircraft flew in formation.',exfr:'Les deux avions volaient en formation.'},
{en:'to ignore',trap:'ignorer (ne pas savoir)',tru:'ne pas tenir compte de',fr:'ignorer (ne pas savoir)',enFor:'to be unaware of',ex:'Never ignore a warning light.',exfr:'Ne négligez jamais un voyant d\'alarme.'},
{en:'to charge',trap:'charger (cargaison)',tru:'facturer',fr:'charger (cargaison)',enFor:'to load',ex:'The airline charges for extra baggage.',exfr:'La compagnie facture les bagages supplémentaires.'},
{en:'motor',trap:'moteur d\'avion',tru:'moteur électrique',fr:'moteur d\'avion',enFor:'engine',ex:'The aircraft has a single piston engine.',exfr:'L\'avion a un seul moteur à pistons.'},
{en:'agenda',trap:'agenda',tru:'ordre du jour',fr:'agenda (carnet)',enFor:'diary / planner',ex:'The agenda of the briefing is on the board.',exfr:'L\'ordre du jour du briefing est sur le tableau.'},
{en:'journey',trap:'journée',tru:'voyage, trajet',fr:'journée',enFor:'day',ex:'It was a long journey across the Alps.',exfr:'Ce fut un long voyage à travers les Alpes.'},
{en:'evidence',trap:'évidence',tru:'preuve',fr:'évidence',enFor:'obvious',ex:'The investigators found evidence of fatigue.',exfr:'Les enquêteurs ont trouvé des preuves de fatigue.'},
{en:'comprehensive',trap:'compréhensif',tru:'complet, détaillé',fr:'compréhensif',enFor:'understanding',ex:'The captain gave a comprehensive briefing.',exfr:'Le commandant a fait un briefing complet.'},
{en:'sympathetic',trap:'sympathique',tru:'compatissant',fr:'sympathique',enFor:'nice / friendly',ex:'The controller was sympathetic to our problem.',exfr:'Le contrôleur a compati à notre problème.'},
{en:'convenient',trap:'convenable',tru:'pratique',fr:'convenable',enFor:'suitable / decent',ex:'Is this a convenient time to talk?',exfr:'Est-ce un bon moment pour parler ?'}
];

/* Franglais : [[ ]] marque la partie fautive à repérer */
const FRANG=[
['The aircraft landed [[hardly]] and the gear was damaged.','The aircraft landed hard and the gear was damaged.','« Hardly » veut dire « à peine ». Pour « durement », on dit « hard ».'],
['I [[interest by]] aviation.','I am interested in aviation.','On dit « to be interested in » (s\'intéresser à).'],
['To land well, you have [[just to watch]] your speed.','To land well, you just have to watch your speed.','« Just » se place devant « have to » : you just have to.'],
['My friend [[made me discover]] aviation.','My friend introduced me to aviation.','« Make » ne signifie pas « faire découvrir ». On dit « introduce someone to ».'],
['The airfield is [[near from]] the city.','The airfield is near the city.','« Near » est suivi directement du nom, sans « from ».'],
['I [[am agree]] with you.','I agree with you.','« Agree » est un verbe : on ne dit pas « I am agree ».'],
['I [[have]] 22 years.','I am 22 years old.','En anglais, l\'âge se dit avec « to be ».'],
['I [[am flying since]] three years.','I have been flying for three years.','Durée jusqu\'à maintenant : present perfect + « for ».'],
['The engine [[is in panne]].','The engine has failed.','« En panne » se traduit par « has failed » ou « has broken down ».'],
['The weather [[is]] bad since this morning.','The weather has been bad since this morning.','Avec « since », on utilise le present perfect.'],
['[[Actually]] the wind is strong.','Currently the wind is strong.','« Actually » veut dire « en fait ». Pour « actuellement » : « currently ».'],
['He [[explained me]] the procedure.','He explained the procedure to me.','Avec « explain », la personne est introduite par « to ».'],
['There is a lot of [[turbulences]].','There is a lot of turbulence.','« Turbulence » est indénombrable.'],
['The [[informations are]] correct.','The information is correct.','« Information » est indénombrable et ne prend pas de « s ».'],
['Can you give me some [[advices]]?','Can you give me some advice?','« Advice » est indénombrable.'],
['I [[assist to]] a briefing.','I attend a briefing.','« Assister à » se dit « to attend ».'],
['I [[wait]] the clearance.','I am waiting for the clearance.','« Wait » est suivi de « for ».'],
['The runway is [[long of]] 3000 metres.','The runway is 3000 metres long.','La longueur se place avant « long ».'],
['My instructor [[learned]] me to fly.','My instructor taught me to fly.','« Learn » = apprendre ; « teach » = enseigner.'],
['The fuel [[is finished]].','We have run out of fuel.','On dit « to run out of » ou « the fuel is running out ».'],
['It [[depends of]] the wind.','It depends on the wind.','« Depend » se construit avec « on ».'],
['I [[arrived to]] the airport at nine.','I arrived at the airport at nine.','On arrive « at » un aéroport, « in » une ville.'],
['We [[discussed about]] the route.','We discussed the route.','« Discuss » n\'est pas suivi de « about ».'],
['I am waiting [[you]] at the gate.','I am waiting for you at the gate.','« Wait for » + personne.'],
['I [[can\'t to]] land.','I can\'t land.','Après un verbe modal, pas de « to ».'],
['[[In the left]] there is a mountain.','On the left there is a mountain.','On dit « on the left ».'],
['The aircraft is [[heavy loaded]].','The aircraft is heavily loaded.','Adverbe de manière : « heavily ».'],
['I [[have fear]] of thunderstorms.','I am afraid of thunderstorms.','On dit « to be afraid of ».'],
['I [[am use to fly]] at night.','I am used to flying at night.','« Be used to » + verbe en -ing.'],
['The visibility [[is of]] 5 kilometres.','The visibility is 5 kilometres.','Pas de « of » : « is 5 kilometres ».'],
['I flew [[during]] two hours.','I flew for two hours.','Une durée se dit avec « for ».'],
['The plane [[is arrived]].','The plane has arrived.','Avec « arrive », on emploie « have » au present perfect.'],
['My flight [[is cancel]].','My flight is cancelled.','Participe passé : « cancelled ».'],
['[[Which]] time is it?','What time is it?','On dit « What time ».'],
['The captain [[said me]] to wait.','The captain told me to wait.','« Say » ne prend pas de complément de personne direct. On dit « tell someone ».']
];

/* Reformule : décrire un mot sans le dire */
const REFORM=[
{fr:'une manche à air',en:'windsock',def:'It is a cone-shaped tube of fabric on a pole at an airfield. It shows the direction and the strength of the wind.'},
{fr:'des cales',en:'chocks',def:'They are small blocks put in front of and behind the wheels to stop the aircraft from moving when it is parked.'},
{fr:'une barre de remorquage',en:'tow bar',def:'It is a metal bar that connects the nose wheel to a tug, so that people can pull or push the aircraft on the ground.'},
{fr:'une jauge d\'huile',en:'dipstick',def:'It is a long thin stick that you put into the engine to check how much oil there is.'},
{fr:'un décrochage',en:'stall',def:'It happens when the wing no longer produces enough lift because the angle of attack is too high. The aircraft loses height.'},
{fr:'un volet',en:'flap',def:'It is a movable surface on the rear edge of the wing. We lower it to produce more lift at low speed, for take-off and landing.'},
{fr:'le palonnier',en:'rudder pedals',def:'They are two pedals under the pilot\'s feet. They move the rudder and steer the aircraft on the ground.'},
{fr:'un vent de travers',en:'crosswind',def:'It is a wind that blows across the runway, not along it. It makes landing and take-off more difficult.'},
{fr:'le seuil de piste',en:'runway threshold',def:'It is the beginning of the part of the runway that can be used for landing.'},
{fr:'un point d\'arrêt',en:'holding point',def:'It is a place before the runway where an aircraft must stop and wait for permission to enter.'},
{fr:'un casque audio de pilote',en:'headset',def:'It is a device with earphones and a microphone. Pilots wear it to hear the radio and to speak.'},
{fr:'une liste de vérifications',en:'checklist',def:'It is a written list of actions that pilots do step by step, so that they do not forget anything.'},
{fr:'un extincteur',en:'fire extinguisher',def:'It is a red container with a hose. We use it to put out a fire.'},
{fr:'un gilet de sauvetage',en:'life jacket',def:'It is a piece of clothing that keeps you afloat if you land on water.'},
{fr:'une ceinture de sécurité',en:'seat belt',def:'It is a strap that holds you in your seat during take-off, landing and turbulence.'},
{fr:'un hangar',en:'hangar',def:'It is a very large building where aircraft are kept and repaired.'},
{fr:'une tour de contrôle',en:'control tower',def:'It is a tall building at an airport with large windows. Controllers use it to watch aircraft and give instructions.'},
{fr:'un pare-brise',en:'windshield',def:'It is the front window of the aircraft. It protects the pilots from the wind and lets them see outside.'},
{fr:'une hélice',en:'propeller',def:'It is a rotating part with blades, attached to the engine. It pulls the aircraft through the air.'},
{fr:'un anémomètre',en:'airspeed indicator',def:'It is an instrument in the cockpit that shows how fast the aircraft is moving through the air.'},
{fr:'un altimètre',en:'altimeter',def:'It is an instrument that shows how high the aircraft is above sea level.'},
{fr:'un pneu crevé',en:'flat tyre',def:'It is a tyre that has lost its air, so the wheel cannot be used normally.'},
{fr:'un camion-citerne',en:'fuel truck',def:'It is a large vehicle that carries fuel and fills the aircraft tanks.'},
{fr:'un bagage cabine',en:'hand luggage',def:'It is a small bag that a passenger can keep with them in the cabin.'}
];
const REFORM_STARTERS=["It is a thing that…","It is used for…","It looks like…","It is made of…","You can find it…","We use it when…","It is the opposite of…","It is similar to…"];

/* Mayday builder : blocs dans l'ordre standard (station, indicatif, nature, intention, position, autres) */
const MAYDAY=[
{ctx:"Panne moteur à 3000 pieds, vous planez vers un champ. Construisez le message de détresse dans le bon ordre.",
 blocks:["Mayday, Mayday, Mayday","Toulouse Approach, F-GABC","engine failure","forced landing in a field","5 miles north of Toulouse, altitude 3000 feet, heading 180","2 persons on board"]},
{ctx:"Incendie moteur en croisière, vous voulez atterrir immédiatement.",
 blocks:["Mayday, Mayday, Mayday","Lyon Control, Speedbird 452","engine fire","request immediate landing at Lyon","passing flight level 120, heading 090, 25 miles west of Lyon","180 persons on board"]},
{ctx:"Passager malade (urgence sans danger immédiat) : message d'urgence.",
 blocks:["Pan-Pan, Pan-Pan, Pan-Pan","Nice Approach, Airfrans 6742","medical emergency, passenger unconscious","request diversion to Nice","flight level 100, 40 miles south of Nice","120 persons on board"]},
{ctx:"Fumée dans le cockpit, vous revenez vers l'aérodrome de départ.",
 blocks:["Mayday, Mayday, Mayday","Orly Tower, F-GHIJ","smoke in the cockpit","returning to Orly, request priority","3 miles north of the field, altitude 1500 feet","2 persons on board"]},
{ctx:"Fuite de carburant, vous demandez un déroutement.",
 blocks:["Mayday, Mayday, Mayday","Bordeaux Approach, F-GKLM","fuel leak","request immediate diversion to Bordeaux","15 miles west of Bordeaux, altitude 4000 feet","fuel endurance 45 minutes"]},
{ctx:"Perte de pression cabine à haute altitude, descente d'urgence.",
 blocks:["Mayday, Mayday, Mayday","Reims Control, Lufthansa 1HK","loss of cabin pressure","emergency descent to flight level 100","passing flight level 350, heading 270","150 persons on board"]},
{ctx:"Impact d'oiseau au décollage, vous revenez et atterrissez.",
 blocks:["Pan-Pan, Pan-Pan, Pan-Pan","Paris Tower, KLM 1327","bird strike, vibration on engine two","request return and landing runway 26L","just airborne, altitude 1200 feet","160 persons on board"]},
{ctx:"Panne électrique totale, vous continuez à vue.",
 blocks:["Pan-Pan, Pan-Pan, Pan-Pan","Lyon Approach, F-GNOP","electrical failure","request priority landing at Lyon","10 miles east of Lyon, altitude 2500 feet","3 persons on board"]}
];
if(typeof module!=='undefined')module.exports={FF,FRANG,REFORM,MAYDAY};
