/* data-vocab.js : format "français=anglais;" par catégorie */
const CATNAME={
  avion:'Avion et structure',cockpit:'Cockpit et instruments',moteur:'Moteur et systèmes',commandes:'Commandes et aérodynamique',
  prevol:'Prévol et sol',aeroport:'Aéroport et piste',radio:'Radio et ATC',nav:'Navigation',meteo:'Météo',
  urgence:'Urgences et pannes',actions:'Verbes et manœuvres',circuit:'Circuit et approche'
};
const VRAW={
avion:`aile=wing;empennage=tail unit;dérive (empennage)=fin;stabilisateur horizontal=horizontal stabiliser;gouverne de profondeur=elevator;gouverne de direction=rudder;volet=flap;bord d'attaque=leading edge;bord de fuite=trailing edge;saumon d'aile=wingtip;train d'atterrissage=landing gear;train avant=nose gear;train principal=main gear;roue=wheel;pneu=tyre;frein=brake;capot moteur=engine cowling;hélice=propeller;pale=blade;cône d'hélice=spinner;verrière=canopy;pare-brise=windshield;porte=door;trappe de visite=inspection panel;feu de navigation=navigation light;feu anticollision=anti-collision light;feu à éclats=strobe light;phare d'atterrissage=landing light;tube de Pitot=pitot tube;prise statique=static port;compensateur (gouverne)=trim tab;réservoir=fuel tank;bouchon de réservoir=fuel cap;aérofrein=speedbrake;mât réacteur=pylon;soute=cargo hold;cabine=cabin;siège=seat;ceinture de sécurité=seat belt;extincteur=fire extinguisher;gilet de sauvetage=life jacket;canot de survie=life raft;sortie de secours=emergency exit;toboggan=escape slide;train rentrant=retractable landing gear;train fixe=fixed landing gear;jambe de train=landing gear leg;amortisseur=shock absorber`,
cockpit:`tableau de bord=instrument panel;manche=control column;manche latéral=sidestick;palonnier=rudder pedals;manette des gaz=throttle;manette de richesse=mixture control;commande de pas d'hélice=propeller control;commande de volets=flap lever;commande de train=landing gear lever;compensateur (commande)=trim wheel;anémomètre=airspeed indicator;altimètre=altimeter;variomètre=vertical speed indicator;horizon artificiel=attitude indicator;conservateur de cap=heading indicator;coordinateur de virage=turn coordinator;compas magnétique=magnetic compass;indicateur de pression d'huile=oil pressure gauge;indicateur de température d'huile=oil temperature gauge;jauge de carburant=fuel gauge;compte-tours=rev counter;manomètre=pressure gauge;ampèremètre=ammeter;transpondeur=transponder;sélecteur de fréquence=frequency selector;casque=headset;bouton d'émission=push-to-talk button;pilote automatique=autopilot;directeur de vol=flight director;écran de vol principal=primary flight display;écran de navigation=navigation display;radiocompas=automatic direction finder;interrupteur=switch;disjoncteur=circuit breaker;batterie=battery;alternateur=alternator;magnétos=magnetos;contacteur de démarreur=starter switch;réchauffage carburateur=carburettor heat;réchauffage pitot=pitot heat;pompe électrique=electric fuel pump;voyant=warning light;alarme sonore=aural warning;liste de vérifications=checklist;pare-soleil=sun visor;cadran=dial;aiguille=needle;écran=screen;bouton=knob`,
moteur:`moteur à pistons=piston engine;turbopropulseur=turboprop;réacteur=jet engine;hélice à pas variable=variable-pitch propeller;carburateur=carburettor;injection=fuel injection;bougie=spark plug;cylindre=cylinder;vilebrequin=crankshaft;huile=oil;carter d'huile=oil sump;filtre à huile=oil filter;circuit de refroidissement=cooling system;température culasse=cylinder head temperature;température des gaz d'échappement=exhaust gas temperature;pression d'admission=manifold pressure;régime=engine speed;poussée=thrust;puissance=power;ralenti=idle;plein gaz=full throttle;mélange pauvre=lean mixture;mélange riche=rich mixture;carburant=fuel;essence aviation=avgas;kérosène=jet fuel;pompe à carburant=fuel pump;robinet carburant=fuel selector;purge=fuel drain;filtre à carburant=fuel filter;débit carburant=fuel flow;consommation=fuel consumption;autonomie=endurance;démarreur=starter;allumage=ignition;système électrique=electrical system;circuit hydraulique=hydraulic system;pression hydraulique=hydraulic pressure;groupe auxiliaire de puissance=auxiliary power unit;générateur=generator;inverseur de poussée=thrust reverser;givrage carburateur=carburettor icing;échappement=exhaust;surchauffe=overheating;vibrations=vibrations`,
commandes:`portance=lift;traînée=drag;poids=weight;incidence=angle of attack;assiette=pitch attitude;inclinaison=bank angle;roulis=roll;tangage=pitch;lacet=yaw;cabrer=to pitch up;piquer=to pitch down;décrochage=stall;vitesse de décrochage=stall speed;vrille=spin;piqué=dive;ressource=pull-out;virage=turn;virage serré=steep turn;glissade=slip;dérapage=skid;centre de gravité=centre of gravity;masse maximale au décollage=maximum take-off weight;devis de masse et centrage=weight and balance;facteur de charge=load factor;vitesse indiquée=indicated airspeed;vitesse vraie=true airspeed;vitesse sol=ground speed;vitesse de rotation=rotation speed;vitesse de montée=climb speed;vitesse de croisière=cruise speed;vitesse d'approche=approach speed;vitesse maximale=maximum speed;effet de sol=ground effect;turbulence de sillage=wake turbulence;effet de couple=torque effect;finesse=glide ratio;plané=glide;vol en palier=level flight;mise en palier=levelling off`,
prevol:`visite prévol=pre-flight inspection;tour de l'avion=walk-around;cale=chock;barre de remorquage=tow bar;remorquage=towing;repoussage=pushback;avitaillement=refuelling;camion-citerne=fuel truck;prélever un échantillon=to take a fuel sample;eau dans le carburant=water in the fuel;niveau d'huile=oil level;jauge d'huile=dipstick;documents de bord=aircraft documents;carnet de route=technical log;plan de vol=flight plan;dossier météo=weather briefing;briefing=briefing;bagages=baggage;chargement=loading;fret=cargo;passagers=passengers;équipage=crew;commandant de bord=captain;copilote=first officer;instructeur=instructor;élève pilote=student pilot;housse=cover;bouchon pitot=pitot cover;verrou de gouverne=gust lock;liste de contrôle=checklist;dégivrage=de-icing;hangar=hangar;aire de trafic=ramp;fuite=leak;corrosion=corrosion;rayure=scratch;bosse=dent;fissure=crack;usure=wear;jeu=play;serrage=tightness;sécurisé=secure;en place=in place;retiré=removed`,
aeroport:`aérodrome=aerodrome;piste=runway;voie de circulation=taxiway;aire de stationnement=apron;poste de stationnement=stand;point d'arrêt=holding point;seuil de piste=runway threshold;seuil décalé=displaced threshold;axe de piste=runway centreline;bord de piste=runway edge;marquage=marking;balisage lumineux=lighting;feux de bord de piste=runway edge lights;feux d'axe=centreline lights;feux d'approche=approach lights;manche à air=windsock;tour de contrôle=control tower;aérogare=terminal;passerelle=boarding bridge;porte d'embarquement=gate;pompiers=fire service;véhicule de piste=airport vehicle;voiture de guidage=follow-me car;panneau=sign;prolongement d'arrêt=stopway;prolongement dégagé=clearway;longueur de piste=runway length;piste mouillée=wet runway;piste contaminée=contaminated runway;piste glissante=slippery runway;neige=snow;flaque d'eau=standing water;revêtement=surface;herbe=grass;bitume=asphalt;béton=concrete;clôture=fence;obstacle=obstacle;terre-plein=grass area;aire de demi-tour=turning area`,
radio:`émission=transmission;réception=reception;fréquence=frequency;indicatif=callsign;message=message;autorisation=clearance;instruction=instruction;relecture=readback;accusé de réception=acknowledgement;répétez=say again;parlez lentement=speak slower;attendez=standby;reçu=roger;je me conforme=wilco;affirmatif=affirm;négatif=negative;impossible=unable;correction=correction;ignorez=disregard;confirmez=confirm;premier contact=initial call;comment me recevez-vous=how do you read;fort et clair=loud and clear;grésillement=static;mauvaise réception=poor reception;panne radio=radio failure;fréquence encombrée=busy frequency;changer de fréquence=change frequency;écouter la fréquence=monitor the frequency;quitter la fréquence=leave the frequency;contrôleur=controller;contrôle d'approche=approach control;contrôle en route=area control;service d'information de vol=flight information service;affichez le code=squawk;identification=ident;contact radar=radar contact;guidage radar=radar vectors;alphabet=phonetic alphabet;chiffre=digit;heure UTC=UTC time;message d'urgence=urgency message;message de détresse=distress message;parlez=go ahead;terminé=out`,
nav:`cap=heading;route=track;cap magnétique=magnetic heading;route vraie=true track;déclinaison magnétique=magnetic variation;dérive (vent)=drift;vent de face=headwind;vent arrière (composante)=tailwind;vent de travers=crosswind;point de report=reporting point;point tournant=waypoint;balise=beacon;relèvement=bearing;distance=distance;durée du vol=flight time;heure estimée d'arrivée=estimated time of arrival;carte aéronautique=aeronautical chart;échelle=scale;navigation à l'estime=dead reckoning;navigation à vue=visual navigation;point d'appui=landmark;cours d'eau=river;autoroute=motorway;voie ferrée=railway;lac=lake;côte=coast;montagne=mountain;vallée=valley;relief=terrain;altitude minimale de sécurité=minimum safe altitude;niveau de vol=flight level;altitude=altitude;hauteur=height;niveau de transition=transition level;altitude de transition=transition altitude;calage altimétrique=altimeter setting;espace aérien=airspace;zone réglementée=restricted area;zone interdite=prohibited area;zone dangereuse=danger area;zone de contrôle=control zone;région de contrôle terminale=terminal control area;route aérienne=airway;point d'entrée=entry point;point de sortie=exit point;déviation=deviation;direct=direct routing;au nord de=north of;au sud de=south of;à l'est de=east of;à l'ouest de=west of;à proximité de=close to`,
meteo:`vent=wind;direction du vent=wind direction;force du vent=wind speed;rafales=gusts;vent variable=variable wind;calme=calm;visibilité=visibility;portée visuelle de piste=runway visual range;brouillard=fog;brume=mist;brume sèche=haze;plafond=ceiling;base des nuages=cloud base;sommet des nuages=cloud top;nuage=cloud;ciel dégagé=clear sky;peu nuageux=few;épars=scattered;fragmenté=broken;couvert=overcast;orage=thunderstorm;éclair=lightning;pluie=rain;averse=shower;bruine=drizzle;grêle=hail;pluie verglaçante=freezing rain;givrage=icing;givre=frost;turbulence=turbulence;cisaillement de vent=windshear;ondes orographiques=mountain waves;courant ascendant=updraught;courant descendant=downdraught;microrafale=microburst;température=temperature;point de rosée=dew point;humidité=humidity;pression atmosphérique=atmospheric pressure;anticyclone=high pressure area;dépression=low pressure area;front froid=cold front;front chaud=warm front;prévision=forecast;amélioration=improvement;dégradation=deterioration;en baisse=decreasing;en hausse=increasing;sec=dry;mouillé=wet;ensoleillé=sunny;nuageux=cloudy`,
urgence:`détresse=distress;urgence=urgency;panne moteur=engine failure;panne sèche=fuel exhaustion;fuite de carburant=fuel leak;incendie=fire;incendie moteur=engine fire;fumée=smoke;odeur de brûlé=burning smell;perte de pression cabine=loss of cabin pressure;descente d'urgence=emergency descent;masque à oxygène=oxygen mask;panne électrique=electrical failure;panne hydraulique=hydraulic failure;panne de transpondeur=transponder failure;panne d'instrument=instrument failure;train bloqué=gear stuck;volets bloqués=flaps jammed;commande bloquée=jammed control;perte de contrôle=loss of control;collision avec un oiseau=bird strike;impact de foudre=lightning strike;givrage sévère=severe icing;passager malade=sick passenger;urgence médicale=medical emergency;atterrissage forcé=forced landing;atterrissage de précaution=precautionary landing;amerrissage=ditching;évacuation=evacuation;personnes à bord=persons on board;autonomie restante=remaining endurance;carburant minimum=minimum fuel;position incertaine=uncertain of position;perdu=lost;déroutement=diversion;demi-tour=turn back;équipes de secours=emergency services;ambulance=ambulance;détournement=hijack;interférence illicite=unlawful interference;alerte à la bombe=bomb threat;panne=failure;défaillance=malfunction;anomalie=abnormality;avarie=damage`,
actions:`décoller=to take off;atterrir=to land;monter=to climb;descendre=to descend;maintenir=to maintain;virer=to turn;poursuivre=to continue;rapporter=to report;contacter=to contact;attendre=to hold;s'aligner=to line up;rouler=to taxi;s'arrêter=to stop;traverser=to cross;dégager=to vacate;remettre les gaz=to go around;rejoindre=to join;quitter=to leave;survoler=to overfly;éviter=to avoid;réduire=to reduce;augmenter=to increase;accélérer=to accelerate;ralentir=to slow down;sortir les volets=to extend the flaps;rentrer les volets=to retract the flaps;sortir le train=to lower the landing gear;rentrer le train=to raise the landing gear;couper=to shut down;allumer=to switch on;éteindre=to switch off;démarrer=to start;vérifier=to check;annuler=to cancel;reprendre=to resume;s'établir=to become established;intercepter=to intercept;suivre=to follow;dépasser=to overtake;céder le passage=to give way;prévenir (avertir)=to warn;empêcher=to prevent;se dérouter=to divert;revenir=to return;ne pas tenir compte de=to ignore;déclarer=to declare;demander=to request;approuver=to approve;refuser=to deny`,
circuit:`circuit d'aérodrome=traffic pattern;vent arrière (circuit)=downwind leg;branche de base=base leg;finale=final;branche vent traversier=crosswind leg;montée initiale=initial climb;virage de base=base turn;verticale terrain=overhead;tour de piste=circuit;posé-décollé=touch-and-go;passage bas=low pass;arrondi=flare;trajectoire=flight path;plan de descente=glide path;pente d'approche=approach slope;trop haut=too high;trop bas=too low;trop vite=too fast;trop lent=too slow;approche stabilisée=stabilised approach;approche interrompue=missed approach;approche à vue=visual approach;approche aux instruments=instrument approach;alignement de piste=localiser;alignement de descente=glide slope;hauteur de décision=decision height;altitude minimale de descente=minimum descent altitude;point d'approche initiale=initial approach fix;point de toucher des roues=touchdown point;zone de toucher des roues=touchdown zone;roulage à l'atterrissage=landing roll;freinage=braking;numéro un=number one;séquence d'atterrissage=landing sequence;espacement=spacing;trafic=traffic;trafic en vue=traffic in sight;trafic à suivre=traffic to follow;conflit=conflict;collision=collision;attente (hippodrome)=holding pattern;virage d'attente=procedure turn`
};
const VOC=[];
Object.keys(VRAW).forEach(c=>{
  VRAW[c].split(';').forEach(p=>{
    p=p.trim();if(!p)return;
    const i=p.indexOf('=');
    const fr=p.slice(0,i).trim(),en=p.slice(i+1).trim();
    if(fr&&en&&fr.toLowerCase()!==en.toLowerCase()&&!VOC.some(v=>v.fr===fr&&v.en===en))VOC.push({fr,en,cat:c});
  });
});
if(typeof module!=='undefined')module.exports={VOC,CATNAME,VRAW};
